### ISSUE TITLE
Suggestion to add a Bill of Materials (BOM) to the Guide

### ISSUE THREAD

**Issue by Simonalle** [FlyingT/OctoTouch#1]
Hey there, how about adding a bill of materials (Raspberry Pi 3/3+/4/4+; Touchscreen, cable, etc.) to the introduction to the Guide?

Thanks for the write up. Looking forward to doing this on my Mk3S!

**Comment by FlyingT** [comment]
I thought about it, but it really comes down to a Pi 3, 5V power supply and any 3,5" touchscreen.
Will add it anyway, thanks for the suggestion!

**Comment by FlyingT** [comment]
Added
